#!/bin/bash -l

set -euo pipefail
WANDB_ENTITY="${WANDB_ENTITY:-}"
WANDB_MODE="${WANDB_MODE:-online}"

# Original loop/template
# # londonsmartmeter contextual sweep for gale_adam_r
# for lr_decay in 0.98 0.99 0.995; do
#   for context_tag in l d ld; do
#     case "$context_tag" in
#       l) contexts='[l]' ;;
#       d) contexts='[d]' ;;
#       ld) contexts='[l,d]' ;;
#     esac
#     for ridge_alpha in 0.1 1.0 10.0; do
#       python -m appfl_sim.runner \
#         --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml \
#           "logging.configs.wandb_entity=${WANDB_ENTITY}" \
#           "logging.configs.wandb_mode=${WANDB_MODE}" \
#           logging.configs.wandb_group=gale_adam_r \
#           "logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep" \
#           optimizer.lr_decay.enable=true \
#           optimizer.lr=0.001 \
#           optimizer.lr_decay.gamma=$lr_decay \
#           algorithm.scheduler_kwargs.discount_gamma=0.80 \
#           algorithm.scheduler_kwargs.exploration_beta=0.001 \
#           algorithm.scheduler_kwargs.ridge_alpha=$ridge_alpha \
#           algorithm.scheduler_kwargs.reward_scale=1 \
#           "algorithm.scheduler_kwargs.contexts=${contexts}" \
#           experiment.name=GALE_LONDONSMARTMETER_SWEEP \
#           logging.name="sweep_londonsmartmeter_gale_adam_r_80_0.001_${lr_decay}_${context_tag}_${ridge_alpha}" &
#     done
#   done
#   wait
# done

# Flattened commands
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_l_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_l_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_l_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_d_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_d_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_d_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_ld_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_ld_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.98 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.98_ld_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_l_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_l_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_l_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_d_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_d_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_d_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_ld_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_ld_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.99 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.99_ld_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_l_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_l_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_l_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_d_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_d_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_d_10.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=0.1 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_ld_0.1
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=1.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_ld_1.0
CUDA_VISIBLE_DEVICES= python -m appfl_sim.runner --config appfl_sim/config/cross-device/londonsmartmeter/gale_adam_r.yaml logging.configs.wandb_entity=${WANDB_ENTITY} logging.configs.wandb_mode=${WANDB_MODE:-online} logging.configs.wandb_group=gale_adam_r logging.configs.wandb_tags=cross-device,londonsmartmeter,gale_adam_r,sweep optimizer.lr_decay.enable=true optimizer.lr=0.001 optimizer.lr_decay.gamma=0.995 algorithm.scheduler_kwargs.discount_gamma=0.80 algorithm.scheduler_kwargs.exploration_beta=0.001 algorithm.scheduler_kwargs.ridge_alpha=10.0 algorithm.scheduler_kwargs.reward_scale=1 algorithm.scheduler_kwargs.contexts=[l,d] experiment.name=GALE_LONDONSMARTMETER_SWEEP logging.name=sweep_londonsmartmeter_gale_adam_r_80_0.001_0.995_ld_10.0
