experiment:
  name: GenFL_20NewsGroups
  seed: 42
  device: cuda
  server_device: cuda
  backend: serial
  stateful: true
dataset:
  path: ./data
  name: 20NewsGroups
  backend: sklearn
  download: true
  configs:
    remove:
    - headers
    - footers
    - quotes
split:
  type: dirichlet
  configs:
    dirichlet_alpha: 0.1
    dirichlet_min_size: 100
model:
  name: distilbert-base-uncased
  backend: hf
  configs:
    pretrained: true
    hf_task: sequence_classification
    use_model_tokenizer: true
    seq_len: 256
train:
  num_rounds: 100
  num_clients: 20
  num_sampled_clients: 20
  update_base: epoch
  local_epochs: 1
  batch_size: 64
  num_workers: 2
  train_pin_memory: true
  eval_pin_memory: false
  shuffle: true
  eval_batch_size: 16
algorithm:
  name: fedprox
  mix_coefs: sample_ratio
  optimize_memory: true
  aggregator: FedproxAggregator
  scheduler: FedproxScheduler
  trainer: FedproxTrainer
  aggregator_kwargs:
    client_weights_mode: sample_ratio
  scheduler_kwargs:
    reward_scale: 10.0
  trainer_kwargs:
    mu: 0.001
loss:
  name: CrossEntropyLoss
  backend: torch
optimizer:
  name: AdamW
  backend: auto
  lr: 5.0e-5
  lr_decay:
    enable: false
  clip_grad_norm: 1.0
  configs:
    weight_decay: 0.01
eval:
  every: 20
  metrics:
  - acc1
  - acc5
  do_pre_evaluation: true
  do_post_evaluation: false
  show_eval_progress: true
  enable_global_eval: true
  enable_federated_eval: false
  configs:
    scheme: dataset
    dataset_ratio:
    - 70
    - 20
    - 10
logging:
  path: ./log
  name: 20newsgroups_diri_fedprox
  backend: wandb
  type: server_only
  configs:
    track_gen_rewards: true
    wandb_mode: online
    wandb_entity: ""
